# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 11:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170725_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='date_created',
        ),
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 25, 11, 48, 36, 436296, tzinfo=utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
